name: failures
description: A new Flutter package project.
version: 0.0.1
author: SSebigo
homepage: https://gitlab.com/codename-wine/wine

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  very_good_analysis: ^1.0.4

flutter: null
