name: wine_packages

packages:
  - packages/**

scripts:
  # Analyze the project for Dart analysis issues.
  #  - Requires `pub global activate tuneup`.
  analyze: >
    melos exec -c 1 --fail-fast -- \
      pub global run tuneup check
  # Formats the code of all packages (Java, Objective-C, and Dart).
  #  - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
  #  - Requires `git`.
  #  - Requires `clang-format` (can be installed via Brew on MacOS).
  format: pub global run flutter_plugin_tools format

  # Run standard flutter tests in all packages that have them.
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore="*example*" --ignore="*web*" -- \
      flutter test

dev_dependencies:
  very_good_analysis: ^1.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"