name: wine
description: A collaborative social reading platorm.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  assorted_layout_widgets: 9.0.0
  auto_route: 7.8.4
  bloc: 8.1.2
  cached_network_image: 3.3.0
  cloud_firestore: 4.13.2
  collection: 1.18.0
  devicelocale: 0.7.0
  equatable: 2.0.5
  firebase_auth: 4.14.1
  firebase_core: 2.23.0
  firebase_storage: 11.5.2
  flare_flutter: 3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_quill: 8.6.3
  flutter_staggered_grid_view: 0.7.0
  freezed_annotation: 2.4.1
  get_it: 7.6.4
  google_sign_in: 6.1.6
  image_cropper: 5.0.1
  image_picker: 1.0.4
  injectable: 2.3.2
  intl: 0.18.1
  json_annotation: 4.8.1
  like_button: 2.0.5
  line_icons: 2.0.3
  measure_size: 4.0.0
  mime: 1.0.5
  oxidized: 6.1.0
  path: 1.9.0
  path_provider: 2.1.1
  percent_indicator: 4.2.3
  readmore: 2.2.0
  responsive_builder: 0.7.0
  shared_preferences: 2.2.2
  string_validator: 1.0.2
  stringr: 1.0.0
  time: 2.1.3
  uuid: 4.2.1

dev_dependencies:
  auto_route_generator: 7.3.2
  bloc_test: 9.1.5
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  injectable_generator: 2.4.1
  json_serializable: 6.7.1
  mocktail: 1.0.1
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
