name: wine
description: WINE is a collaborative story writing app based on a tree of possibilities.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  cloud_firestore: ^1.0.7
  cupertino_icons: ^1.0.3
  devicelocale: ^0.4.1
  equatable: ^2.0.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  flare_flutter: ^3.0.0
  flare_loading: ^3.0.0
  flutter_bloc: ^7.0.0
  flutter_icons: ^1.1.0
  freezed_annotation: ^0.14.1
  get_it: ^7.1.3
  google_sign_in: ^5.0.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  injectable: ^1.4.0
  introduction_screen: ^2.1.0
  json_annotation: ^4.0.1
  line_icons: ^2.0.1
  logger: ^1.0.0
  mime: ^1.0.0
  path_provider: ^2.0.1
  rustic: ^0.3.0
  simple_gesture_detector: ^0.2.0
  string_validator: ^0.3.0
  stringr: ^0.0.2-prerelease
  time: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  bloc_test: ^8.0.0
  build_runner: ^2.0.3
  flutter_flavorizr: ^2.0.0
  fluttericon: ^2.0.0
  freezed: ^0.14.1+3
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.0
  json_serializable: ^4.1.1
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.3

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    beta:
      app:
        name: "WINE Beta"

      android:
        applicationId: "io.killy.wine.beta"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.beta"
        generateDummyAssets: false

    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
