name: wine
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  bloc: ^6.1.3
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  equatable: ^2.0.0
  firebase_auth: ^1.0.1
  flutter_bloc: ^6.1.3
  freezed_annotation: "0.12.0"
  get_it: ^6.0.0
  google_sign_in: ^5.0.0
  hive: ^2.0.0
  injectable: ^1.2.0
  uuid: ^3.0.1
  validators: ^2.0.1

dependency_overrides:
  analyzer: ^1.1.0
  args: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  json_annotation: ^4.0.0
  yaml: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.5
  flutter_flavorizr: ^1.0.9
  freezed: "0.12.7"
  hive_generator: ^1.0.0
  injectable_generator: ^1.2.0
  very_good_analysis: ^2.0.0

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    beta:
      app:
        name: "WINE Beta"

      android:
        applicationId: "io.killy.wine.beta"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.beta"
        generateDummyAssets: false

    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

flutter:
  uses-material-design: true
