name: wine
description: WINE is a collaborative story writing app based on a tree of possibilities.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  assorted_layout_widgets: 8.0.4
  auto_route: 7.5.0
  bloc: 8.1.2
  cached_network_image: 3.2.3
  cloud_firestore: 4.8.2
  cupertino_icons: 1.0.5
  devicelocale: 0.6.0
  equatable: 2.0.5
  firebase_auth: 4.6.3
  firebase_core: 2.14.0
  firebase_storage: 11.2.4
  flare_flutter: 3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_quill: 7.2.10
  flutter_staggered_grid_view: 0.6.2
  freezed_annotation: 2.2.0
  get_it: 7.6.0
  google_sign_in: 6.1.4
  image_cropper: 4.0.1
  image_picker: 1.0.0
  injectable: 2.1.2
  intl: 0.18.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  json_annotation: 4.8.1
  like_button: 2.0.5
  line_icons: 2.0.1
  logger: 1.4.0
  measured_size: 1.0.0
  mime: 1.0.4
  oxidized: 6.0.0
  path: 1.8.3
  path_provider: 2.0.15
  percent_indicator: 4.2.3
  readmore: 2.2.0
  responsive_builder: 0.7.0
  shimmer: 3.0.0
  simple_gesture_detector: 0.2.0
  string_validator: 1.0.0
  stringr: 1.0.0
  time: 2.1.3
  uuid: 3.0.7

dependency_overrides:
  image: 3.0.2
  xml: 5.0.0

dev_dependencies:
  auto_route_generator: 7.1.1
  bloc_test: 9.1.3
  build_runner: 2.4.6
  fake_cloud_firestore: 2.4.1+1
  flutter_flavorizr: 2.2.1
  flutter_launcher_icons_maker: 0.10.2
  flutter_native_splash: 2.3.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  injectable_generator: 2.1.6
  isar_generator: 3.1.0+1
  json_serializable: 6.7.1
  mockito: 5.4.2
  mocktail: 0.3.0
  very_good_analysis: 5.0.0+1

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

# Add macos & windows when ready
flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/launcher/ic_launcher.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"

  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/logo.png"
    icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
