name: wine
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  flutter_flavorizr: ^1.0.9
  very_good_analysis: ^1.0.4

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    beta:
      app:
        name: "WINE Beta"

      android:
        applicationId: "io.killy.wine.beta"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.beta"
        generateDummyAssets: false

    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

flutter:
  uses-material-design: true
