name: wine
description: WINE is a collaborative story writing app based on a tree of possibilities.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^1.0.2
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  equatable: ^2.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flare_loading: ^2.1.2
  flutter_bloc: ^7.0.0
  flutter_icons: ^1.1.0
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  google_sign_in: ^5.0.1
  hive: ^2.0.0
  injectable: ^1.2.2
  json_annotation: ^4.0.1
  logger: ^1.0.0
  path_provider: ^2.0.1
  uuid: ^3.0.1
  validators: ^2.0.1

dependency_overrides:
  analyzer: ^1.2.0
  basic_utils: ^2.6.3
  build: ^2.0.0
  checked_yaml: ^2.0.1
  convert: ^3.0.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  json_annotation: ^4.0.1
  logging: ^1.0.0
  source_gen: ^1.0.0
  yaml: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.2
  build_runner: ^1.12.2
  flutter_flavorizr: ^1.0.10
  freezed: ^0.14.1+1
  hive_generator: ^1.0.0
  injectable_generator: ^1.2.2
  json_serializable: ^4.1.0
  very_good_analysis: ^2.0.0

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    beta:
      app:
        name: "WINE Beta"

      android:
        applicationId: "io.killy.wine.beta"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.beta"
        generateDummyAssets: false

    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
