name: wine
description: WINE is a collaborative story writing app based on a tree of possibilities

publish_to: none

version: 0.5.2+113

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assorted_layout_widgets: ^3.0.1
  auto_route: ^0.6.9
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.16.0+1
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  equatable: ^1.2.6
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flare_flutter: ^2.0.6
  flare_loading: ^2.1.1
  flutter_bloc: ^6.1.2
  flutter_device_locale: ^0.4.0
  flutter_icons: ^1.1.0
  flutter_markdown: ^0.5.2
  flutter_native_splash: ^0.3.0
  flutter_staggered_grid_view: ^0.3.4
  flutter_stringprocess: ^0.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.6
  google_sign_in: ^4.5.9
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  injectable: ^1.0.7
  intl: ^0.16.1
  logger: ^0.9.4
  package_info: ^0.4.3+4
  path_provider: ^1.6.27
  percent_indicator: ^2.1.9+1
  string_validator: ^0.1.4
  swipe_gesture_recognizer: ^0.0.2
  time: ^1.4.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  bloc_test: ^7.1.0
  build_runner: ^1.11.1
  faker: ^1.3.0
  flutter_flavorizr: ^1.0.9
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.7
  hive_generator: ^0.8.2
  injectable_generator: ^1.1.0
  mockito: ^4.1.4
  very_good_analysis: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/ic_launcher.png"

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    beta:
      app:
        name: "WINE Beta"

      android:
        applicationId: "io.killy.wine.beta"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.beta"
        generateDummyAssets: false

    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
