name: wine
description: WINE is a collaborative story writing app based on a tree of possibilities.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  assorted_layout_widgets: 7.0.0
  auto_route: 5.0.4
  bloc: 8.1.1
  cached_network_image: 3.2.3
  cloud_firestore: 4.4.4
  cupertino_icons: 1.0.5
  devicelocale: 0.6.0
  equatable: 2.0.5
  firebase_auth: 4.2.10
  firebase_core: 2.7.1
  firebase_storage: 11.0.15
  flare_flutter: 3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  flutter_quill: 6.4.4
  flutter_staggered_grid_view: 0.6.2
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  google_sign_in: 6.0.2
  image_cropper: 3.0.1
  image_picker: 0.8.7
  injectable: 2.1.0
  intl: 0.18.0
  isar: 3.0.5
  isar_flutter_libs: 3.0.5
  json_annotation: 4.8.0
  like_button: 2.0.5
  line_icons: 2.0.1
  logger: 1.2.2
  measured_size: 1.0.0
  mime: 1.0.4
  oxidized: 5.3.0
  path: 1.8.3
  path_provider: 2.0.13
  percent_indicator: 4.2.3
  readmore: 2.2.0
  responsive_builder: 0.6.4
  shimmer: 2.0.0
  simple_gesture_detector: 0.2.0
  string_validator: 1.0.0
  stringr: 1.0.0
  time: 2.1.3
  uuid: 3.0.7

dependency_overrides:
  analyzer: 5.2.0
  ffi: 2.0.1
  image: 3.0.2
  intl: 0.18.0
  path: 1.8.3
  xml: 5.0.0

dev_dependencies:
  auto_route_generator: 5.0.3
  bloc_test: 9.1.1
  build_runner: 2.3.3
  fake_cloud_firestore: 2.4.0
  flutter_flavorizr: 2.1.5
  flutter_launcher_icons_maker: 0.10.2
  flutter_native_splash: 2.2.19
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  injectable_generator: 2.1.4
  isar_generator: 3.0.5
  json_serializable: 6.6.1
  mockito: 5.3.2
  mocktail: 0.3.0
  very_good_analysis: 4.0.0+1

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

# Add macos & windows when ready
flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/launcher/ic_launcher.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"

  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/logo.png"
    icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
