name: wine
description: WINE is a collaborative story writing app based on a tree of possibilities.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^7.0.0
  auto_route: ^5.0.4
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.5
  devicelocale: ^0.5.5
  equatable: ^2.0.5
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_quill: ^6.1.7
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  injectable: ^2.1.0
  intl: ^0.18.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.7.0
  like_button: ^2.0.5
  line_icons: ^2.0.1
  logger: ^1.1.0
  measured_size: ^1.0.0
  mime: ^1.0.3
  oxidized: ^5.2.0
  path: ^1.8.3
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  readmore: ^2.2.0
  responsive_builder: ^0.4.3
  shimmer: ^2.0.0
  simple_gesture_detector: ^0.2.0
  string_validator: ^0.3.0
  stringr: ^1.0.0
  time: ^2.1.3
  uuid: ^3.0.7

dependency_overrides:
  intl: 0.18.0
  path: 1.8.3

dev_dependencies:
  auto_route_generator: ^5.0.3
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  fake_cloud_firestore: ^2.1.0
  flutter_flavorizr: ^2.1.5
  flutter_launcher_icons_maker: ^0.10.2
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  isar_generator: ^3.0.5
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

# Add macos & windows when ready
flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/launcher/ic_launcher.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"

  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/logo.png"
    icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
