name: wine
description: WINE is a collaborative story writing app based on a tree of possibilities.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 0.6.9
  cloud_firestore: 0.16.0+1
  cupertino_icons: 1.0.0
  dartz: ^0.9.2
  equatable: 1.2.6
  firebase_auth: 0.20.0+1
  firebase_core: 0.7.0
  flare_loading: ^2.1.2
  flutter_bloc: 6.1.3
  flutter_device_locale: 0.4.0
  flutter_icons: ^1.1.0
  flutter_stringprocess: ^0.1.2
  freezed_annotation: 0.12.0
  get_it: 5.0.6
  google_sign_in: 4.5.9
  hive: 1.5.0-pre
  hive_flutter: 0.3.1
  injectable: 1.1.2
  introduction_screen: 1.0.9
  json_annotation: 3.1.1
  logger: 0.9.4
  mime: 0.9.7
  path_provider: 1.6.28
  string_validator: 0.1.4
  uuid: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 0.6.10
  bloc_test: 7.1.0
  build_runner: 1.11.1
  flutter_flavorizr: ^1.0.11
  freezed: 0.12.7
  hive_generator: 0.8.2
  injectable_generator: 1.1.2
  json_serializable: 3.5.1
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.3

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    beta:
      app:
        name: "WINE Beta"

      android:
        applicationId: "io.killy.wine.beta"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.beta"
        generateDummyAssets: false

    development:
      app:
        name: "WINE Dev"

      android:
        applicationId: "io.killy.wine.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine.dev"
        generateDummyAssets: false

    production:
      app:
        name: "WINE"

      android:
        applicationId: "io.killy.wine"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.wine"
        generateDummyAssets: false

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
