part of 'new_chapter_database_bloc.dart';

@freezed
abstract class NewChapterDatabaseState with _$NewChapterDatabaseState {
  const factory NewChapterDatabaseState({
    @required ChapterDraft chapterDraft,
    @required bool isEditMode,
    @required String coverUrl,
    @required Title title,
    @required String titleStr,
    @required int titleWordCount,
    @required Story story,
    @required String storyStr,
    @required int storyWordCount,
    @required Genre genre,
    @required String genreStr,
    @required Genre genreOptional,
    @required String genreOptionalStr,
    @required Language language,
    @required String languageStr,
    @required Copyrights copyrights,
    @required String copyrightsStr,
    @required bool isNSFW,
    @required bool isEnd,
    @required bool isPublishingOrSaving,
    @required bool isPublishedOrSaved,
    @required bool isFirstChapter,
    @required Map<String, String> genresMap,
    @required Map<String, String> languagesMap,
    @required Map<String, String> copyrightsMap,
    @required bool showErrorMessages,
    @required
        Option<Either<DatabaseFailure, dynamic>> databaseFailureOrSuccessOption,
  }) = _NewChapterPageState;

  factory NewChapterDatabaseState.initial() => NewChapterDatabaseState(
        chapterDraft: ChapterDraft(),
        isEditMode: false,
        coverUrl: '',
        title: Title(''),
        titleStr: '',
        titleWordCount: 0,
        story: Story(''),
        storyStr: '',
        storyWordCount: 0,
        genre: Genre(''),
        genreStr: '',
        genreOptional: Genre('', isOptional: true),
        genreOptionalStr: '',
        language: Language(''),
        languageStr: '',
        copyrights: Copyrights(''),
        copyrightsStr: '',
        isNSFW: false,
        isEnd: false,
        isPublishingOrSaving: false,
        isPublishedOrSaved: false,
        isFirstChapter: false,
        genresMap: <String, String>{},
        languagesMap: <String, String>{},
        copyrightsMap: <String, String>{},
        showErrorMessages: false,
        databaseFailureOrSuccessOption: none(),
      );
}
