part of 'new_chapter_database_bloc.dart';

@freezed
abstract class NewChapterDatabaseState with _$NewChapterDatabaseState {
  const factory NewChapterDatabaseState({
    @required bool isDeletingOrPublishingOrSaving,
    @required bool isEditMode,
    @required bool isEnd,
    @required bool isFirstChapter,
    @required bool isNSFW,
    @required bool showErrorMessages,
    @required ChapterDraft chapterDraft,
    @required Copyrights copyrights,
    @required Genre genre,
    @required Genre genreOptional,
    @required int storyWordCount,
    @required int titleWordCount,
    @required Language language,
    @required Map<String, String> copyrightsMap,
    @required Map<String, String> genresMap,
    @required Map<String, String> languagesMap,
    @required Option<Either<DatabaseFailure, dynamic>> databaseFailureOrSuccessOption,
    @required Story story,
    @required String chapterCoverUrl,
    @required String copyrightsStr,
    @required String coverUrl,
    @required String genreOptionalStr,
    @required String genreStr,
    @required String languageStr,
    @required String seriesCoverUrl,
    @required String storyStr,
    @required String titleStr,
    @required TextEditingController storyController,
    @required TextEditingController titleController,
    @required Title title,
  }) = _NewChapterDatabaseState;

  factory NewChapterDatabaseState.initial() => NewChapterDatabaseState(
        chapterCoverUrl: '',
        chapterDraft: ChapterDraft(),
        copyrights: Copyrights(''),
        copyrightsMap: <String, String>{},
        copyrightsStr: '',
        coverUrl: '',
        databaseFailureOrSuccessOption: none(),
        genre: Genre(''),
        genreOptional: Genre('', isOptional: true),
        genreOptionalStr: '',
        genresMap: <String, String>{},
        genreStr: '',
        isDeletingOrPublishingOrSaving: false,
        isEditMode: false,
        isEnd: false,
        isFirstChapter: false,
        isNSFW: false,
        language: Language(''),
        languagesMap: <String, String>{},
        languageStr: '',
        seriesCoverUrl: '',
        showErrorMessages: false,
        story: Story(''),
        storyController: TextEditingController(),
        storyStr: '',
        storyWordCount: 0,
        title: Title(''),
        titleController: TextEditingController(),
        titleStr: '',
        titleWordCount: 0,
      );
}
