name: models
description: A new Flutter package project.
version: 0.0.1
author: SSebigo
homepage: https://gitlab.com/codename-wine/wine

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  equatable: ^1.2.5
  firebase_auth: ^0.20.0+1
  flutter_stringprocess: ^0.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  mockito: ^4.1.4
  very_good_analysis: ^1.0.4

flutter: null
