name: utils
description: A new Flutter package project.
version: 0.0.1
author: SSebigo
homepage: https://gitlab.com/codename-wine/wine

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  time: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4

flutter: null
